/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ProjetoRaell.view;

import br.com.ProjetoRaell.dao.CompraDao;
import br.com.ProjetoRaell.model.Compra;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/** 
 *
 * @author silva
 */
public class frmBancoCompra extends javax.swing.JFrame {

    /**
     * Creates new form frmBancoCompra
     */
    public frmBancoCompra() {
        initComponents();
    }
    
    public void listar(){
        CompraDao dao = new CompraDao();
        List<Compra> compras = dao.listarCompras();
        DefaultTableModel dados = (DefaultTableModel)tbCompras.getModel();
        dados.setNumRows(0);
        
        for (Compra compra : compras) {
            dados.addRow(new Object[]{
                compra.getFlavor(),
                compra.getShape(),
                compra.getQuantity()
                
                
            });
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tbCompras = new javax.swing.JTable();
        btHome = new javax.swing.JButton();
        txtPesquisar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btPesquisar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1406, 735));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        tbCompras.setBackground(new java.awt.Color(255, 137, 196));
        tbCompras.setForeground(new java.awt.Color(255, 255, 255));
        tbCompras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Flavor", "Shape", "Quantity"
            }
        ));
        tbCompras.setMaximumSize(new java.awt.Dimension(2147483644, 80));
        tbCompras.setSelectionBackground(new java.awt.Color(255, 102, 204));
        tbCompras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbComprasMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbCompras);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(110, 220, 1180, 380);

        btHome.setBackground(new java.awt.Color(255, 137, 196));
        btHome.setFont(new java.awt.Font("Agency FB", 0, 30)); // NOI18N
        btHome.setForeground(new java.awt.Color(255, 255, 255));
        btHome.setText("Home");
        btHome.setBorder(null);
        btHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHomeActionPerformed(evt);
            }
        });
        getContentPane().add(btHome);
        btHome.setBounds(650, 600, 140, 90);

        txtPesquisar.setBackground(new java.awt.Color(242, 141, 196));
        txtPesquisar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtPesquisar.setForeground(new java.awt.Color(255, 255, 255));
        txtPesquisar.setBorder(null);
        getContentPane().add(txtPesquisar);
        txtPesquisar.setBounds(651, 82, 560, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ProjetoRaell/imagens/purchasertable.jpeg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -30, 1840, 760);

        btPesquisar.setText("jButton1");
        btPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarActionPerformed(evt);
            }
        });
        getContentPane().add(btPesquisar);
        btPesquisar.setBounds(1210, 92, 40, 30);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        listar();
    }//GEN-LAST:event_formWindowActivated

    private void tbComprasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbComprasMouseClicked
        // TODO add your handling code here:
        frmCompra comp = new frmCompra();
        comp.setVisible(true);
        
        comp.cbFlavor.setSelectedItem(tbCompras.getValueAt(tbCompras.getSelectedRow(), 0).toString());
        comp.cbShape.setSelectedItem(tbCompras.getValueAt(tbCompras.getSelectedRow(), 1).toString());
        comp.txtQuantityy.setText(tbCompras.getValueAt(tbCompras.getSelectedRow(), 2).toString());
                
     
    }//GEN-LAST:event_tbComprasMouseClicked

    private void btHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHomeActionPerformed
        // TODO add your handling code here:
        frmHome home = new frmHome();
        home.setVisible(true);
        dispose();
    }//GEN-LAST:event_btHomeActionPerformed

    private void btPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarActionPerformed
        // TODO add your handling code here:
         String flavor = "%" +  txtPesquisar.getText() + "%";
         
        CompraDao dao = new CompraDao();
        List<Compra> compras = dao.buscarCompra(flavor);
        DefaultTableModel dados = (DefaultTableModel)tbCompras.getModel();
        dados.setNumRows(0);
        
        for (Compra compra : compras) {
            dados.addRow(new Object[]{
                compra.getFlavor(),
                compra.getShape(),
                compra.getQuantity()
                
                
            });
        }
        
    }//GEN-LAST:event_btPesquisarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmBancoCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmBancoCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmBancoCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmBancoCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmBancoCompra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btHome;
    private javax.swing.JButton btPesquisar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbCompras;
    private javax.swing.JTextField txtPesquisar;
    // End of variables declaration//GEN-END:variables
}
