/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ProjetoRaell.view;

import br.com.ProjetoRaell.dao.ClienteDao;
import br.com.ProjetoRaell.model.Cliente;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author silva 
 */
public class frmBancoCliente extends javax.swing.JFrame {

    /**
     * Creates new form frmBancoCliente
     */
    public frmBancoCliente() {
        initComponents();
    }
    
    public void listar(){
        ClienteDao dao = new ClienteDao();
        List<Cliente> clientes = dao.listarClientes();
        DefaultTableModel dados = (DefaultTableModel)tbClientes.getModel();
        dados.setNumRows(0);
        
        for (Cliente cliente : clientes) {
            dados.addRow(new Object[]{
                cliente.getId(),
                cliente.getNome(),
                cliente.getTelefone(),
                cliente.getCep(),
                cliente.getCidade(),
                cliente.getEstado(),
                cliente.getRua(),
                cliente.getQuantity()
                
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbClientes = new javax.swing.JTable();
        btHome = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1406, 735));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        tbClientes.setBackground(new java.awt.Color(255, 137, 196));
        tbClientes.setForeground(new java.awt.Color(255, 255, 255));
        tbClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Nome", "Telefone", "CEP", "Cidade", "Estado", "Rua/Avenida", "Quantity"
            }
        ));
        tbClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbClientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbClientes);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(280, 70, 840, 510);

        btHome.setBackground(new java.awt.Color(255, 137, 196));
        btHome.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btHome.setForeground(new java.awt.Color(255, 255, 255));
        btHome.setText("Home");
        btHome.setBorder(null);
        btHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btHomeMouseClicked(evt);
            }
        });
        getContentPane().add(btHome);
        btHome.setBounds(650, 600, 140, 90);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\silva\\OneDrive\\Documentos\\NetBeansProjects\\ProjetoRaell\\src\\br\\com\\ProjetoRaell\\imagens\\banco.jpeg")); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 1400, 700);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        listar();
        
    }//GEN-LAST:event_formWindowActivated

    private void btHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btHomeMouseClicked
        // TODO add your handling code here:
        frmHome home = new frmHome();
        home.setVisible(true);
    }//GEN-LAST:event_btHomeMouseClicked

    private void tbClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbClientesMouseClicked
        // TODO add your handling code here:
        frmCliente cli = new frmCliente();
        cli.setVisible(true);
        
        cli.txtId.setText(tbClientes.getValueAt(tbClientes.getSelectedRow(), 0).toString());
        cli.txtNome.setText(tbClientes.getValueAt(tbClientes.getSelectedRow(), 1).toString());
        cli.txtTelefone.setText(tbClientes.getValueAt(tbClientes.getSelectedRow(), 2).toString());
        cli.txtCep.setText(tbClientes.getValueAt(tbClientes.getSelectedRow(), 3).toString());
        cli.txtCidade.setText(tbClientes.getValueAt(tbClientes.getSelectedRow(), 4).toString());
        cli.txtEstado.setText(tbClientes.getValueAt(tbClientes.getSelectedRow(), 5).toString());
        cli.txtRua.setText(tbClientes.getValueAt(tbClientes.getSelectedRow(), 6).toString());
        cli.txtQuan.setText(tbClientes.getValueAt(tbClientes.getSelectedRow(), 7).toString());
                
    }//GEN-LAST:event_tbClientesMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmBancoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmBancoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmBancoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmBancoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmBancoCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btHome;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbClientes;
    // End of variables declaration//GEN-END:variables
}
