/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ProjetoRaell.view;

import br.com.ProjetoRaell.dao.ClienteDao;
import br.com.ProjetoRaell.dao.CompraDao;
import br.com.ProjetoRaell.model.Compra;

/**
 *
 * @author silva
 */
public class frmCompra extends javax.swing.JFrame {

    /**
     * Creates new form frmCompra
     */
    public frmCompra() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        txtQuantity = new javax.swing.JTextField();
        btSalvarr = new javax.swing.JButton();
        cbShape = new javax.swing.JComboBox<>();
        cbFlavor = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButton1.setBackground(new java.awt.Color(255, 137, 196));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("+");
        jButton1.setBorder(null);
        getContentPane().add(jButton1);
        jButton1.setBounds(140, 290, 50, 50);

        txtQuantity.setBackground(new java.awt.Color(255, 137, 196));
        txtQuantity.setBorder(null);
        getContentPane().add(txtQuantity);
        txtQuantity.setBounds(1055, 267, 190, 80);

        btSalvarr.setBackground(new java.awt.Color(255, 102, 255));
        btSalvarr.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btSalvarr.setForeground(new java.awt.Color(255, 255, 255));
        btSalvarr.setText("Save");
        btSalvarr.setBorder(null);
        btSalvarr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarrActionPerformed(evt);
            }
        });
        getContentPane().add(btSalvarr);
        btSalvarr.setBounds(1190, 592, 140, 80);

        cbShape.setBackground(new java.awt.Color(255, 0, 153));
        cbShape.setForeground(new java.awt.Color(255, 255, 255));
        cbShape.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbShape.setBorder(null);
        cbShape.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbShapeActionPerformed(evt);
            }
        });
        getContentPane().add(cbShape);
        cbShape.setBounds(625, 266, 410, 80);

        cbFlavor.setBackground(new java.awt.Color(255, 0, 153));
        cbFlavor.setForeground(new java.awt.Color(255, 255, 255));
        cbFlavor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbFlavor.setBorder(null);
        cbFlavor.setVerifyInputWhenFocusTarget(false);
        cbFlavor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbFlavorActionPerformed(evt);
            }
        });
        getContentPane().add(cbFlavor);
        cbFlavor.setBounds(200, 267, 410, 80);

        jLabel1.setBackground(new java.awt.Color(255, 153, 204));
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\silva\\OneDrive\\Documentos\\NetBeansProjects\\ProjetoRaell\\src\\br\\com\\ProjetoRaell\\imagens\\compra.jpeg")); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-8, 0, 1490, 700);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbShapeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbShapeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbShapeActionPerformed

    private void cbFlavorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbFlavorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbFlavorActionPerformed

    private void btSalvarrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarrActionPerformed
        // TODO add your handling code here:
         Compra comp = new Compra();
         
         comp.setFlavor(cbFlavor.getSelectedItem().toString());
         comp.setShape(cbShape.getSelectedItem().toString());
         comp.setQuantity(Integer.parseInt(txtQuantity.getText()));
       
        
        CompraDao dao = new CompraDao();
        dao.salvarCompra(comp);
    }//GEN-LAST:event_btSalvarrActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmCompra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btSalvar;
    private javax.swing.JButton btSalvar1;
    private javax.swing.JButton btSalvarr;
    private javax.swing.JComboBox<String> cbFlavor;
    private javax.swing.JComboBox<String> cbShape;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtQuantity;
    // End of variables declaration//GEN-END:variables
}
