/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ProjetoRaell.view;

import br.com.ProjetoRaell.dao.CompraDao;
import br.com.ProjetoRaell.model.Compra;

/**
 *
 * @author silva
 */
public class frmCompra extends javax.swing.JFrame {

    /**
     * Creates new form frmCompra
     */
    public frmCompra() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btNovo = new javax.swing.JButton();
        txtQuantityy = new javax.swing.JTextField();
        btSalvarr = new javax.swing.JButton();
        cbShape = new javax.swing.JComboBox<>();
        cbFlavor = new javax.swing.JComboBox<>();
        btExcluir = new javax.swing.JButton();
        btEditar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btHome = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1406, 735));
        setResizable(false);
        getContentPane().setLayout(null);

        btNovo.setBackground(new java.awt.Color(255, 137, 196));
        btNovo.setForeground(new java.awt.Color(255, 255, 255));
        btNovo.setText("+");
        btNovo.setBorder(null);
        btNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNovoActionPerformed(evt);
            }
        });
        getContentPane().add(btNovo);
        btNovo.setBounds(137, 290, 50, 50);

        txtQuantityy.setBackground(new java.awt.Color(255, 137, 196));
        txtQuantityy.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtQuantityy.setForeground(new java.awt.Color(255, 255, 255));
        txtQuantityy.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtQuantityy.setBorder(null);
        getContentPane().add(txtQuantityy);
        txtQuantityy.setBounds(1047, 270, 190, 80);

        btSalvarr.setBackground(new java.awt.Color(255, 137, 196));
        btSalvarr.setFont(new java.awt.Font("Agency FB", 0, 30)); // NOI18N
        btSalvarr.setForeground(new java.awt.Color(255, 255, 255));
        btSalvarr.setText("Save");
        btSalvarr.setBorder(null);
        btSalvarr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarrActionPerformed(evt);
            }
        });
        getContentPane().add(btSalvarr);
        btSalvarr.setBounds(775, 600, 140, 90);

        cbShape.setBackground(new java.awt.Color(255, 0, 153));
        cbShape.setForeground(new java.awt.Color(255, 255, 255));
        cbShape.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Formatos:", "Flower 1", "Flower 2", "Flower 3", "Flower 4", "Flower 5", "Flower 6", "Flower 7", "Flower 8", "Flower 9" }));
        cbShape.setBorder(null);
        cbShape.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbShapeActionPerformed(evt);
            }
        });
        getContentPane().add(cbShape);
        cbShape.setBounds(620, 270, 410, 80);

        cbFlavor.setBackground(new java.awt.Color(255, 0, 153));
        cbFlavor.setForeground(new java.awt.Color(255, 255, 255));
        cbFlavor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sabores:", "Tradicional", "0% Lactose", "0% Glúten", "0% Açúcar", "Fitness", "Ninho", "Prestígio", "Oreo", "Recheio de Chocolate" }));
        cbFlavor.setBorder(null);
        cbFlavor.setVerifyInputWhenFocusTarget(false);
        cbFlavor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbFlavorActionPerformed(evt);
            }
        });
        getContentPane().add(cbFlavor);
        cbFlavor.setBounds(198, 270, 410, 80);

        btExcluir.setBackground(new java.awt.Color(255, 137, 196));
        btExcluir.setFont(new java.awt.Font("Agency FB", 0, 30)); // NOI18N
        btExcluir.setForeground(new java.awt.Color(255, 255, 255));
        btExcluir.setText("Delete");
        btExcluir.setBorder(null);
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(btExcluir);
        btExcluir.setBounds(458, 600, 140, 90);

        btEditar.setBackground(new java.awt.Color(255, 137, 196));
        btEditar.setFont(new java.awt.Font("Agency FB", 0, 30)); // NOI18N
        btEditar.setForeground(new java.awt.Color(255, 255, 255));
        btEditar.setText("Edit");
        btEditar.setBorder(null);
        btEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditarActionPerformed(evt);
            }
        });
        getContentPane().add(btEditar);
        btEditar.setBounds(617, 600, 140, 90);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\silva\\OneDrive\\Documentos\\NetBeansProjects\\ProjetoRaell\\src\\br\\com\\ProjetoRaell\\imagens\\compra .jpeg")); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(-13, -10, 1400, 720);

        btHome.setBackground(new java.awt.Color(255, 137, 196));
        btHome.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        btHome.setForeground(new java.awt.Color(255, 255, 255));
        btHome.setText("Home");
        btHome.setBorder(null);
        btHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btHomeMouseClicked(evt);
            }
        });
        getContentPane().add(btHome);
        btHome.setBounds(560, 90, 280, 70);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cbShapeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbShapeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbShapeActionPerformed

    private void cbFlavorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbFlavorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbFlavorActionPerformed

    private void btSalvarrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarrActionPerformed
        // TODO add your handling code here:
        
        
         Compra comp = new Compra();
         
         comp.setFlavor(cbFlavor.getSelectedItem().toString());
         comp.setShape(cbShape.getSelectedItem().toString());
         comp.setQuantity(Integer.parseInt(txtQuantityy.getText()));
       
        
        CompraDao dao = new CompraDao();
        dao.salvarCompra(comp);
        
        
         
    }//GEN-LAST:event_btSalvarrActionPerformed

    private void btEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditarActionPerformed
        // TODO add your handling code here:
        Compra comp = new Compra();
         
         comp.setFlavor(cbFlavor.getSelectedItem().toString());
         comp.setShape(cbShape.getSelectedItem().toString());
         comp.setQuantity(Integer.parseInt(txtQuantityy.getText()));
       
        
        CompraDao dao = new CompraDao();
        dao.editarCompra(comp);
        
        
    }//GEN-LAST:event_btEditarActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        // TODO add your handling code here:
        Compra comp = new Compra();
         
         comp.setFlavor(cbFlavor.getSelectedItem().toString());
         
       
        
        CompraDao dao = new CompraDao();
        dao.excluirCompra(comp);
        
    }//GEN-LAST:event_btExcluirActionPerformed

    private void btNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNovoActionPerformed
        // TODO add your handling code here:
        cbFlavor.setSelectedItem("Sabores:");
        cbShape.setSelectedItem("Formatos:");
        txtQuantityy.setText("");
        
        
    }//GEN-LAST:event_btNovoActionPerformed

    private void btHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btHomeMouseClicked
        // TODO add your handling code here:
        var home = new frmHome();
        home.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_btHomeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmCompra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btEditar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btHome;
    private javax.swing.JButton btNovo;
    private javax.swing.JButton btSalvarr;
    public javax.swing.JComboBox<String> cbFlavor;
    public javax.swing.JComboBox<String> cbShape;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JTextField txtQuantityy;
    // End of variables declaration//GEN-END:variables
}
