/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ProjetoRaell.view;

import br.com.ProjetoRaell.dao.ClienteDao;
import br.com.ProjetoRaell.model.Cliente;

/**
 *
 * @author silva
 */
public class frmCliente extends javax.swing.JFrame {

    /**
     * Creates new form frmCliente
     */
    public frmCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        txtCidade = new javax.swing.JTextField();
        txtEstado = new javax.swing.JTextField();
        txtRua = new javax.swing.JTextField();
        txtQuan = new javax.swing.JTextField();
        btSalvar = new javax.swing.JButton();
        txtCep = new javax.swing.JFormattedTextField();
        txtTelefone = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jTextField1.setBackground(new java.awt.Color(255, 137, 196));
        jTextField1.setBorder(null);
        jTextField1.setSelectionColor(new java.awt.Color(153, 255, 0));
        getContentPane().add(jTextField1);
        jTextField1.setBounds(180, 194, 88, 80);

        txtNome.setBackground(new java.awt.Color(255, 137, 196));
        txtNome.setBorder(null);
        getContentPane().add(txtNome);
        txtNome.setBounds(287, 194, 570, 80);

        txtCidade.setBackground(new java.awt.Color(255, 137, 196));
        txtCidade.setBorder(null);
        getContentPane().add(txtCidade);
        txtCidade.setBounds(527, 328, 330, 80);

        txtEstado.setBackground(new java.awt.Color(255, 137, 196));
        txtEstado.setBorder(null);
        getContentPane().add(txtEstado);
        txtEstado.setBounds(882, 328, 330, 80);

        txtRua.setBackground(new java.awt.Color(255, 137, 196));
        txtRua.setBorder(null);
        getContentPane().add(txtRua);
        txtRua.setBounds(176, 463, 830, 80);

        txtQuan.setBackground(new java.awt.Color(255, 137, 196));
        txtQuan.setBorder(null);
        txtQuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuanActionPerformed(evt);
            }
        });
        getContentPane().add(txtQuan);
        txtQuan.setBounds(1025, 463, 190, 80);

        btSalvar.setBackground(new java.awt.Color(255, 137, 196));
        btSalvar.setFont(new java.awt.Font("Segoe UI Emoji", 0, 24)); // NOI18N
        btSalvar.setForeground(new java.awt.Color(255, 255, 255));
        btSalvar.setText("Save");
        btSalvar.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(btSalvar);
        btSalvar.setBounds(1210, 600, 110, 60);

        txtCep.setBackground(new java.awt.Color(255, 137, 196));
        txtCep.setBorder(null);
        try {
            txtCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(txtCep);
        txtCep.setBounds(177, 329, 330, 80);

        txtTelefone.setBackground(new java.awt.Color(255, 137, 196));
        txtTelefone.setBorder(null);
        try {
            txtTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-#### ")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(txtTelefone);
        txtTelefone.setBounds(882, 194, 333, 80);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\silva\\OneDrive\\Documentos\\NetBeansProjects\\ProjetoRaell\\src\\br\\com\\ProjetoRaell\\imagens\\cliente.jpeg")); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-7, 0, 1480, 700);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtQuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuanActionPerformed

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        // TODO add your handling code here:
        Cliente cli = new Cliente();
        
        cli.setNome(txtNome.getText());
        cli.setTelefone(txtTelefone.getText());
        cli.setCep(txtCep.getText());
        cli.setCidade(txtCidade.getText());
        cli.setEstado(txtEstado.getText());
        cli.setRua(txtRua.getText());
        cli.setQuantity(Integer.parseInt(txtQuan.getText()));
        
        ClienteDao dao = new ClienteDao();
        dao.salvarCliente(cli);
        
        
    }//GEN-LAST:event_btSalvarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JFormattedTextField txtCep;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtEstado;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtQuan;
    private javax.swing.JTextField txtRua;
    private javax.swing.JFormattedTextField txtTelefone;
    // End of variables declaration//GEN-END:variables
}
