/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ProjetoRaell.view;

import java.awt.Color;



/**
 *
 * @author silva
 */
public class frmLogin extends javax.swing.JFrame {

    /**
     * Creates new form frmLogin
     */
    public frmLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        spUser = new javax.swing.JTextField();
        spPassword = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1289, 670));
        setResizable(false);
        getContentPane().setLayout(null);

        spUser.setBackground(new java.awt.Color(242, 141, 196));
        spUser.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        spUser.setForeground(new java.awt.Color(255, 255, 255));
        spUser.setBorder(null);
        spUser.setCaretColor(new java.awt.Color(255, 255, 255));
        spUser.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        spUser.setDoubleBuffered(true);
        spUser.setSelectedTextColor(new java.awt.Color(255, 255, 255));
        spUser.setSelectionColor(new java.awt.Color(255, 255, 255));
        spUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spUserActionPerformed(evt);
            }
        });
        getContentPane().add(spUser);
        spUser.setBounds(127, 263, 520, 60);

        spPassword.setBackground(new java.awt.Color(242, 141, 196));
        spPassword.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        spPassword.setForeground(new java.awt.Color(255, 255, 255));
        spPassword.setBorder(null);
        spPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(spPassword);
        spPassword.setBounds(127, 390, 520, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ProjetoRaell/imagens/loginn.jpeg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-10, -90, 1340, 830);

        jButton1.setBackground(new java.awt.Color(255, 102, 255));
        jButton1.setFont(new java.awt.Font("Agency FB", 0, 30)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 0, 204));
        jButton1.setText("Go");
        jButton1.setBorder(null);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(290, 510, 230, 70);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void spUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spUserActionPerformed
        // TODO add your handling code here:
        spUser.setForeground(Color.red);
  
       
    }//GEN-LAST:event_spUserActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        frmHome home = new frmHome();
        home.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void spPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_spPasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField spPassword;
    private javax.swing.JTextField spUser;
    // End of variables declaration//GEN-END:variables
}
